### PR TITLE
Automate binary release

### PR DESCRIPTION
**Pull request by jamezpolley**
Once we have Actions in place and running CI, we can experiment with using Actions to automate binary releases as well.

### CODE REVIEW

**Comment by mlandauer** [comment]
@jamezpolley any update?

**Comment by jamezpolley** [comment]
I'll look at this today.

**Comment by jamezpolley** [comment]
To trigger this, go to https://github.com/openaustralia/yinyo/releases and create a new release.

Once the release is created, the action fires - see https://github.com/openaustralia/yinyo/runs/390524174 for an example. It runs through the same tests that were run on push; assuming they pass, the yinyo binary gets added to the release. See https://github.com/openaustralia/yinyo/releases/tag/v0.0.2-alpha5 for the Release corresponding to the run above.

This only produces a binary with `GOOS=linux` `GOARCH=amd64` binary because I think that's all we need for now. It's easy to add other builds.

It just calls the binary `yinyo`.

Improvements I can think of:

- [ ] Add version number into filename
- [ ] Add os/arch into filename

I think we'd want `v0.0.2-alpha5` to produce `yinyo_0.0.2-alpha5_linux_amd64`.

@mlandauer my feeling is that we merge this as-is and create issues for the enhancements. Does that work for you?

**Comment by jamezpolley** [comment]
See https://github.com/openaustralia/yinyo/releases/tag/v0.0.2-alpha8 - now produces binaries for `linux` on `386`, `amd64`, `arm`, and `arm64`

I've also added in caching for go modules and the go build cache. The cache action doesn't work on release though, and in any case only seems to make a small difference to the time taken.

I'm going to go ahead and merge.

**Pull request merged**
